<?php
    $container = $this->container;
    $maxDepth = $this->navigation('navigation')->menu()->getMaxDepth();
    $minDepth = $this->navigation('navigation')->menu()->getMinDepth();
    $onlyActive = false;
    $indent = '';
    $ulClass = '';
    $addClassToListItem = true;
    
    $html = '';
    
    $found = $this->navigation('navigation')->menu()->findActive($container, $minDepth, $maxDepth);
    if ($found) {
        $foundPage  = $found['page'];
        $foundDepth = $found['depth'];
    } else {
        $foundPage = null;
    }

    $iterator = new RecursiveIteratorIterator($container, RecursiveIteratorIterator::SELF_FIRST);
    if (is_int($maxDepth)) {
        $iterator->setMaxDepth($maxDepth);
    }

    $prevDepth = -1;
    foreach ($iterator as $page) {
        $depth = $iterator->getDepth();
        $isActive = $page->isActive(true);
        if ($depth < $minDepth || !$this->navigation('navigation')->menu()->accept($page)) {
            continue;
        } elseif ($onlyActive && !$isActive) {
            $accept = false;
            if ($foundPage) {
                if ($foundPage->hasPage($page)) {
                    $accept = true;
                } elseif ($foundPage->getParent()->hasPage($page)) {
                    if (!$foundPage->hasPages() ||
                        is_int($maxDepth) && $foundDepth + 1 > $maxDepth) {
                        $accept = true;
                    }
                }
            }

            if (!$accept) {
                continue;
            }
        }

        $depth -= $minDepth;
        $myIndent = $indent . str_repeat('        ', $depth);

        if ($depth > $prevDepth) {
            if ($ulClass && $depth ==  0) {
                $ulClass = ' class="' . $ulClass . '"';
            } else {
                if($depth > 0){
                    $ulClass = ' class="collapse"';
                } else {
                    $ulClass = '';
                }
            }
            $html .= $myIndent . '<ul ' . $ulClass . '>' . PHP_EOL;
        } elseif ($prevDepth > $depth) {
            for ($i = $prevDepth; $i > $depth; $i--) {
                $ind = $indent . str_repeat('        ', $i);
                $html .= $ind . '    </li>' . PHP_EOL;
                $html .= $ind . '</ul>' . PHP_EOL;
            }
            $html .= $myIndent . '    </li>' . PHP_EOL;
        } else {
            $html .= $myIndent . '    </li>' . PHP_EOL;
        }

        $liClasses = array();
        
        if ($addClassToListItem && $page->getClass()) {
            $liClasses[] = $page->getClass();
        }
        if ($isActive) {
            $liClasses[] = 'active';
        }
        
        $liClass = empty($liClasses) ? '' : ' class="' . implode(' ', $liClasses) . '"';

        $html .= $myIndent . '    <li' . $liClass . '>' . PHP_EOL . $myIndent . '        ';
        if($depth == 0 && isset($page->icon)){
            $html .= '<img src="' . $page->icon . '" />';
        }
        if($depth == 0 && count($page->getPages()) > 0){
            $html .= '<a href="javascript:void(0);"><span class="menutext">' . $this->translate($page->getLabel()) . '</span><span class="count">' . count($page->getPages()) . '</span></a>' . PHP_EOL;
        } else {
            $html .= '<a href="' . $page->getHref() . '"><span class="menutext">' . $this->translate($page->getLabel()) . '</span></a>' . PHP_EOL;
        }
        $html .= '<div class="clearfix"></div>';
        $prevDepth = $depth;
    }

    if ($html) {
        for ($i = $prevDepth+1; $i > 0; $i--) {
            $myIndent = $indent . str_repeat('        ', $i-1);
            $html .= $myIndent . '    </li>' . PHP_EOL
                . $myIndent . '</ul>' . PHP_EOL;
        }
        $html = rtrim($html, PHP_EOL);
    }
    
    print $html;
?>